CREATE DATABASE IF NOT EXISTS Livraria;
USE Livraria;

CREATE TABLE Clientes (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    nomeCliente VARCHAR(100) NOT NULL,
    emailCliente VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE Compras (
    CompraID INT PRIMARY KEY AUTO_INCREMENT,
    ClienteID INT NOT NULL,
    NomeLivro VARCHAR(100) NOT NULL,
    FOREIGN KEY (ClienteID) REFERENCES Clientes(ID)
);
